server:
  port: 8082

spring:
   datasource:
     url: jdbc:mysql://localhost:3306/microservices1
     username: root
     password: Comingsoon#12
   jpa:
     hibernate:
       ddl-auto: update
     show-sql: true
   application:
     name: HOTEL-SERVICE
   config:              # for config server
     import: optional:configserver:http://localhost:8085


#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka